Repository Automattic/newspack-ios, pull requests merged in 2020-12, with the labels that each got.

#125 Update WPAuthenticator to 1.30.0
  Newspack/Newspack/Authentication/AuthenticationManager.swift
  Podfile
  Podfile.lock
Labels: Authentication

#123 Issues/117 enable video part 3
  Newspack/Newspack.xcodeproj/project.pbxproj
  Newspack/Newspack/Controllers/AssetsViewController.swift
  Newspack/Newspack/Controllers/MediaDetailViewController.swift
  Newspack/Newspack/Controllers/ToolbarViewController.swift
  Newspack/Newspack/Models/StoryAsset+CoreDataClass.swift
  Newspack/Newspack/Storyboards/Base.lproj/Main.storyboard
  Newspack/Newspack/Storyboards/MainStoryboard.swift
  Newspack/NewspackFramework/Utils/ImageMaker.swift
  Newspack/NewspackShare/Controllers/ShareMediaViewController.swift
Labels: Video

#127 Update WPAuthenticator to 1.31.0-beta
  Newspack/Newspack/Authentication/AuthenticationManager.swift
  Podfile
  Podfile.lock
Labels: enhancement
